# Generated by Django 3.2 on 2022-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('release_date', models.DateField(default=None)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
